### ISSUE TITLE
第一周任务 py103 ch0每天记录

### ISSUE THREAD

**Issue by juthy1** [juthy1/Python-#2]
主要的疑问是python3与2的兼容性问题，刚开始学的时候，好像英文里说不用装3，用2.7就可以，后来看了Q和S知道以后主要用3，果断下了安装，都是用谷歌搜索的，安装完成后，又看了下相关的介绍，及两个的区别。开始跑ex1.py，改完之后，把要打印的内容加上括号（），跑起来就是报错
juxiaosongdeMacBook-Pro:~ juxiaosong$ python3
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
上面是安装后的显示
juxiaosongdeMacBook-Pro:python juxiaosong$ ls
mystuff
juxiaosongdeMacBook-Pro:python juxiaosong$ cd mystuff
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex1.py
  File "ex1.py", line 12
    print （"Hello World!"）
          ^
SyntaxError: Missing parentheses in call to 'print'
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex1.py
  File "ex1.py", line 12
    print （"Hello World!"）
          ^
SyntaxError: Missing parentheses in call to 'print'
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex3.py
  File "ex3.py", line 3
    print "I will now count my chickens:"
                                        ^
SyntaxError: Missing parentheses in call to 'print'
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex1.py
  File "ex1.py", line 12
    print（"Hello World!"）
         ^
SyntaxError: invalid character in identifier
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex1.py
  File "ex1.py", line 12
    print（Hello World!）
              ^
SyntaxError: invalid character in identifier
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex1.py
  File "ex1.py", line 12
    print（“Hello World!”）
               ^
跑个程序，就一直报错。
最后检查发现是因为**# 用了中文输入法输入了括号。**
后面解决了。今天就到这儿了。

**Comment by juthy1** [comment]
print ()在3中是个函数，在括号里，要打的东西，“”引起来的直接打，不引的计算之后打
I will now count my chickens:
Hens
Roosters
Now I will count the eggs:
7.95
Is it trun that 3 + 2 < 5 - 7 ?
False
What is 3 + 2?
What is 5 - 7?
Oh, that's why it's False
How about some more.
Is it greater?
Is it greater or equal?
Is it less or equal?
What will happened?
What will happened?
这是没有在括号里的，有的就打不出来了
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex3.py
I will now count my chickens:
Hens 30.0
Roosters 97
Now I will count the eggs:
6.75
Is it trun that 3 + 2 < 5 - 7 ?
False
What is 3 + 2? 5
What is 5 - 7? -2
Oh, that's why it's False
How about some more.
Is it greater? True
Is it greater or equal? True
Is it less or equal? False
What will happened? 0.5714285714285714
What will happened? 0.5714285714285714
还试验了“/”的作用，在2里，不带小数的除就是整除，之后余数，取整数商。带小数点才计算小数，3里直除了。

**Comment by juthy1** [comment]
关于ex4.py
cars = 100
space_in_a_car = 5.0
drivers = 20
passengers = 90
cars_not_driven = cars - drivers
cars_driven = drivers
carpool_capacity = cars_driven * space_in_a_car
average_passengers_per_car = passengers / cars_driven

print ("There are", cars, "cars available.")
print ("There are only", drivers, "drivers avaiable.")
print ("There will be", cars_not_driven, "empty cars today.")
print ("We can transport", carpool_capacity, "people today.")
print ("We have", passengers, "to carpool today.")
print ("We need to put about", average_passengers_per_car, "in each car.")
在2之中，我把每个车的空间改成了5，司机人减少成了20年，计算的结果，还是每个车4个人。用3计算，为每个车4.5人，说明比前面的计算多了一层，还是没解决完问题，因为人不可能是0.5个。可能是前面设计的问题。
There are 100 cars available.
There are only 20 drivers avaiable.
There will be 80 empty cars today.
We can transport 100.0 people today.
We have 90 to carpool today.
We need to put about 4.5 in each car.

**Comment by juthy1** [comment]
单引号‘’双引号“”三引号“‘”’的作用，单引和双引没有什么区别就是在打引中表示打印引号中的内容，最外面以内的引号也作文本用。三引号相当于分行打，可以省略\n

**Comment by juthy1** [comment]
今天读了http://mp.weixin.qq.com/s?__biz=MzA4ODM4ODQ3MQ==&mid=2651930555&idx=1&sn=d5535c8707dcc9bcf58fe06d73ea0dc3&chksm=8bcf79a3bcb8f0b5dfbd0e5d999f371b39d52a1e3af550303f9bd62e63509dcd92d1d028df90#rd，知道了为了什么要在github上泡了，可是我还没有弄明白，或者是会操作怎么上传呢，以前都是碰的，今天就干这事吧。
执行意图，晚上9点，检查自己有没有学会，如果已经学会，在下面记录下步骤及心得，如果前没时间，还没有会，学会。

**Comment by juthy1** [comment]
下载了GitHub Desktop，正在摸索中

最终还是用的命令上传的，稍后会总结一下，可能上传的人都会了，但是现在的我还不能在不看教程的情况下完成。这个必须要搞定

**Comment by juthy1** [comment]
上传GitHub的命令

1.$ git init  初次设定进度储存库，也就是开始使用 git 来存档。

juxiaosongdeMacBook-Pro:project juxiaosong$ git init
Initialized empty Git repository in /Users/juxiaosong/python/Py103/Chap0/project/.git/
juxiaosongdeMacBook-Pro:project juxiaosong$

2.git add & git status  输入 git add README.md，再输入 git status

juxiaosongdeMacBook-Pro:project juxiaosong$ git add README.md
juxiaosongdeMacBook-Pro:project juxiaosong$ git status
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

	new file:   README.md

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	ex1.py
	ex2.py
	ex3.py
	ex4.py
	ex5.py
	ex6.py
你会发现 README.md 变成绿色，其余的档案还是红色。这表示我们已经预备将 README.md “设定为预备储存进度的档案”。
3.git commit 
git commit -m "add README"  真正将这个档案存进去进度里
juxiaosongdeMacBook-Pro:project juxiaosong$ git commit -m "add README"
[master (root-commit) b974ffb] add README
 1 file changed, 1 insertion(+)
 create mode 100644 README.md
接着我们再输入一遍 git status，发现还是有很多档案，没有被存进去进度区里面。
juxiaosongdeMacBook-Pro:project juxiaosong$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	ex1.py
	ex2.py
	ex3.py
	ex4.py
	ex5.py
	ex6.py

nothing added to commit but untracked files present (use "git add" to track)
juxiaosongdeMacBook-Pro:project juxiaosong$

所以这次我们也要将剩下的档案也存进去进度里面。

输入 git add .，这样就可以把这个目录夹下“所有还没有被加入 git 历史资料库的档案”设为“预备储存”的状态。然后输入 git commit -m "add rest files" 储存剩下所有的档案。

juxiaosongdeMacBook-Pro:project juxiaosong$ git add .
juxiaosongdeMacBook-Pro:project juxiaosong$ git commit -m "add rest files"
[master 0a63f8e] add rest files
 6 files changed, 163 insertions(+)
 create mode 100644 ex1.py
 create mode 100644 ex2.py
 create mode 100644 ex3.py
 create mode 100644 ex4.py
 create mode 100644 ex5.py
 create mode 100644 ex6.py
juxiaosongdeMacBook-Pro:project juxiaosong$ 

4.输入仓库地址就行了

juxiaosongdeMacBook-Pro:project juxiaosong$ git remote add origin https://github.com/juthy1/w0.git
fatal: remote origin already exists.
juxiaosongdeMacBook-Pro:project juxiaosong$ git push -u origin master
Counting objects: 11, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (11/11), 2.92 KiB | 0 bytes/s, done.
Total 11 (delta 0), reused 0 (delta 0)
To https://github.com/juthy1/w0.git
 * [new branch]      master -> master
Branch master set up to track remote branch master from origin.
juxiaosongdeMacBook-Pro:project juxiaosong$ 

成功上传

**Comment by juthy1** [comment]
今天看了他们的Gitbook，自己还是没头绪，应该不难，但是卡在登录Gitbook的帐号密码老是提示错。

1. 他们反应的python2和python3不兼容的问题好像在Mac上不存在。
juxiaosongdeMacBook-Pro:~ juxiaosong$ python
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()

juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()

这两个同时在，而且都可以运行程序。

2.运行了一下%
相当于代入方程式的样子。
x = "There are %d types of people." % 5
#binary = "binary"
binary = "binary"
do_not = "don't"
#do_not = "don't"
#y = "Those who know %s and those who %s." % (binary, do_not)
y = "those who know %s and those who %s." % (binary, do_not)
print(x)
print (y)

There are 5 types of people.
those who know binary and those who don't.

>

**Comment by juthy1** [comment]
参加同学聚会，没有带电脑，一天时间，就感觉不太愿意写了，坐在电脑前也懒了许多。
就使用偷懒的法宝————#**就是绝不偷懒**
今天接着把Gitbook弄了下，能上了，用Github的帐户已经成功登录了，就是编辑起来还有些费劲，明天要学一下Markdown

继续 python3 ex7.py
Mary had a little lamb.
Its fleece was white as %s.
Traceback (most recent call last):
  File "ex7.py", line 6, in <module>
    print ("Its fleece was white as %s.") % 'snow'
TypeError: unsupported operand type(s) for %: 'NoneType' and 'str'
报错了，原来我
print ("Its fleece was white as %s.") % 'snow'
没有把后面的括号进来，导致S没有办法赋值。
改后再跑：
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex7.py
Mary had a little lamb.
Its fleece was white as snow.
And everywhere that Mary went.
..........
Cheese
Burger
晚安，我这不是去睡觉，是去准备明天的工作。

**Comment by juthy1** [comment]
今天已经有了新的任务
请你在本章课程时间内，完成一个最简天气查询程序，运行在命令行界面，实现以下功能：

- 输入城市名，返回该城市的天气数据；

- 输入指令，打印帮助文档（一般用h或help）；

- 输入指令，退出程序的交互（一般使用quit或exit）；

- 在退出程序之前，打印查询过的所有城市。

在https://githup.com/AIMinder/Py103/tree/master/Chap1/project
中，有个weather_info.txt文件

发现我已经用了GitHup Desktop把文件pull到本地了
屏幕快照 2017-01-09 下午11.40.34
还有什么方法呢？

**Comment by juthy1** [comment]
今天跑到ex8.py发现问题了
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex8.py
  File "ex8.py", line 17
    )
    ^
SyntaxError: invalid syntax
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex8.py
Traceback (most recent call last):
  File "ex8.py", line 5, in <module>
    print (fomatter % (1, 2, 3, 4))
NameError: name 'fomatter' is not defined
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex8.py
  File "ex8.py", line 5
    print (fomatter ,% (1, 2, 3, 4))
                     ^
SyntaxError: invalid syntax
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex8.py
  File "ex8.py", line 5
    print (fomatter ,% (1, 2, 3, 4))
                     ^
SyntaxError: invalid syntax
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex8.py
Traceback (most recent call last):
  File "ex8.py", line 5, in <module>
    print (fomatter (1, 2, 3, 4))
NameError: name 'fomatter' is not defined
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex8.py
Traceback (most recent call last):
  File "ex8.py", line 5, in <module>
    print (fomatter) % (1, 2, 3, 4)
NameError: name 'fomatter' is not defined
juxiaosongdeMacBook-Pro:mystuff juxiaosong$ python3 ex8.py
'one' 'two' 'three' 'four'
Traceback (most recent call last):
  File "ex8.py", line 9, in <module>
    print (fomatter % (True, False, False, True))
NameError: name 'fomatter' is not defined
改来改去还是不行
print (fomatter % (1, 2, 3, 4))

##查教程在QA里看到这一句
Why doesn't this work in Python 3?
Don't use Python 3. Use Python 2.7 or better, although Python 2.6 might work fine.
**原来是不能用Python3跑的**
想找个个区别，现在又找不到了，只是记得%的定义不同了。

**Comment by juthy1** [comment]
ex9.py与ex10.py改完基本没有问题。
到ex11.py又出现问题
主要在raw_input()上，在3里是没有这个的，都用input()，改过来解决这事。

**Comment by juthy1** [comment]
Markdown 语法概要

用Markdown写作简易直捷，确实是利器。

排版

换行

这是第一行           # 行末两个空格
这是第二行
粗体

**粗体**
斜体

*斜体*
标题

# 一级标题           # 注意空格
## 二级标题
### 三级标题
列表

- 一级列表           # 注意缩进和空格
  - 二级列表
* 一级列表
  * 二级列表
清单

- [ ] 未完成         # 注意空格
- [x] 已完成
插入

引用

> 引用
文内插入code

`代码代码`
链接

[谷歌](https://google.com)
图片

![苹果]（apple.png）  # 相对路径
提醒
Reference

Markdown | Mastering Markdown
